@startuml

!include ./classesinteraction.plantuml
!include ./factorycreatorclasses.plantuml
top to bottom direction

'removing the interfaces
remove Parser
remove FunctionFactory
remove ArgumentFactory
remove AttributeFactory
remove ClassFactory
remove FunctionProduct
remove ArgumentProduct
remove AttributeProduct
remove ClassProduct

class Translator{
    + Translator(input_language, output_language)
    + Translate(input_files[], output_template)
}

Translator --> ClassFactoryCreator:uses
Translator --> FunctionFactoryCreator:uses
Translator --> AttributeFactoryCreator:uses
Translator --> ArgumentFactoryCreator:uses
Translator --> ParserFactory:uses

@enduml
